<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => 'Kolom',
    'Comma Separated Values' => '',
    'Download exported file' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Non-aktifkan semua popup blocker di browser Anda untuk memastikan proses unduh berjalan lancar',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => 'Ekspor data dalam format yang ditentukan',
    'Exported File' => 'Ekspor File',
    'Generating the export file. Please wait...' => 'Sedang membuat file unduh-an. Silakan tunggu ...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Permintaan disampaikan! Anda dapat menutup dialog ini setelah berkas ter-unduh.',
    'Select Columns' => 'Pilih Kolom',
    'Select columns to export' => 'Pilih kolom untuk di ekspor',
    'Tab Delimited Text' => '',
    'Text' => 'Teks',
    'The CSV export file will be generated for download.' => 'Berkas CSV akan dibuat untuk di-unduh',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Berkas EXCEL 2007+ (xlsx) akan dibuat untuk di-unduh',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Berkas EXCEL 95+ (xls) akan dibuat untuk di-unduh',
    'The HTML export file will be generated for download.' => 'Berkas HTML akan dibuat untuk di-unduh',
    'The PDF export file will be generated for download.' => 'Berkas PDF akan dibuat untuk di-unduh',
    'The TEXT export file will be generated for download.' => 'Berkas TEXT akan dibuat untuk di-unduh',
    'grid-export' => '',
    'Toggle All' => '',
];
