<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Column' => 'Veerg',
    'Comma Separated Values' => 'Komaga eristatud väärtused',
    'Download exported file' => 'Lae eksportitud fail alla',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Luba hüpikaknad, et tagada faili allalaadimise võimalus.',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Export data in selected format' => 'Ekspordi fail valitud formaadis',
    'Exported File' => 'Eksporditud fail',
    'Generating the export file. Please wait...' => 'Genereerin exportditavat faili. Palun oota ...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Grid ekspordi on genereerinud Krajee ExportMenu vidin (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'Kas läheme edasi?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Palve on edastatud! Kui oled faili alla laadinud, võid akna julgesti kinni panna.',
    'Select Columns' => 'Vali veerud',
    'Select columns to export' => 'Vali veerud, mida soovid eksportida',
    'Tab Delimited Text' => 'Tabulaatoriga eraldatud tekst',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'Genereerin CSV faili alla laadimiseks.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Genereerin EXCEL 2007+ (xlsx) faili alla laadimiseks.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Genereerin EXCEL 95+ (xls) faili alla laadimiseks.',
    'The HTML export file will be generated for download.' => 'Genereerin HTML faili alla laadimiseks.',
    'The PDF export file will be generated for download.' => 'Genereerin PDF faili alla laadimiseks.',
    'The TEXT export file will be generated for download.' => 'Genereerin TEXT faili alla laadimiseks.',
    'grid-export' => 'grid-export',
    'Toggle All' => 'Vali kõik',
];
