<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Column' => 'Στήλη',
    'Comma Separated Values' => 'Τιμές διαχωριζόμενες με κόμμα',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Απενεργοποιήστε τους popup blockers του φυλλομετρητή σας για να εξασφαλίσετε ορθή λήψη του αρχείου.',
    'Download exported file' => 'Λήψη του αρχείου',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Export data in selected format' => 'Λήψη των δεδομένων στην επιλεγμένη μορφή',
    'Exported File' => 'Αρχείο ',
    'Generating the export file. Please wait...' => 'Γίνεται δημιουργία του αρχείου δεδομένων. Παρακαλώ περιμένετε...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Grid export generated by Krajee ExportMenu widget (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Input error' => 'Σφάλμα εισόδου',
    'Key' => 'Κλειδί',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'Είστε έτοιμοι;',
    'PDF' => 'PDF',
    'Pick from list' => 'Επιλέξτε από την λίστα',
    'Please pick a value from the drop-down list.' => 'Παρακαλώ επιλέξτε μια τιμή από την λίστα',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Το αίτημα στάλθηκε! Μπορείτε να κλείσετε αυτό το παράθυρο αφού αποθηκεύσετε το αρχείο που κατεβάσατε',
    'Select Columns' => 'Επιλογή στηλών',
    'Select columns to export' => 'Επιλέξτε τις στήλες που θέλετε να εξάγετε',
    'Tab Delimited Text' => 'Tab Delimited Text',
    'Text' => 'Κείμενο',
    'The CSV export file will be generated for download.' => 'Θα δημιουργηθεί το αρχείο δεδομένων σε μορφή CSV.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Θα δημιουργηθεί το αρχείο δεδομένων σε μορφή EXCEL 2007+ (xlsx)',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Θα δημιουργηθεί το αρχείο δεδομένων σε μορφή EXCEL 95+ (xls)',
    'The HTML export file will be generated for download.' => 'Θα δημιουργηθεί το αρχείο δεδομένων σε μορφή HTML.',
    'The PDF export file will be generated for download.' => 'Θα δημιουργηθεί το αρχείο δεδομένων σε μορφή PDF.',
    'The TEXT export file will be generated for download.' => 'Θα δημιουργηθεί το αρχείο δεδομένων σε μορφή TEXT.',
    'Value' => 'Τιμή',
    'Value is not in list.' => 'Η τιμή δεν είναι στη λίστα.',
    'grid-export' => 'grid-export',
    'Toggle All' => '@@@@',
];
