<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Download exported file' => '',
    'Exported File' => '',
    'Input error' => '',
    'Key' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'CSV' => 'CSV',
    'Column' => 'Sloupec',
    'Comma Separated Values' => 'Hodnoty oddělené čárkou',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Pro bezchybné stažení, prosím, vypněte blokování vyskakovacích oken pro tyto webové stránky.',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95+',
    'Export data in selected format' => 'Exportovat data ve zvoleném formátu',
    'Generating the export file. Please wait...' => 'Generuje se soubor. Prosím čekejte...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Export byl vytvořen pomocí Krajee ExportMenu (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Jazyk HTML',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'OK pro pokračování?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Přenositelný formát dokumentu',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Požadavek odeslán! Po stažení souboru můžete toto okno bez obav zavřít.',
    'Select Columns' => 'Zvolte sloupce',
    'Select columns to export' => 'Zvolte sloupce k exportu',
    'Tab Delimited Text' => 'Text oddělený tabulátorem',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'Soubor CSV bude vygenerován a stažen.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Soubor Excel 2007+ (xlsx) bude vygenerován a stažen.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Soubor Excel 95+ (xls) bude vygenerován a stažen.',
    'The HTML export file will be generated for download.' => 'Soubor HTML bude vygenerován a stažen.',
    'The PDF export file will be generated for download.' => 'Soubor PDF bude vygenerován a stažen.',
    'The TEXT export file will be generated for download.' => 'Soubor Text bude vygenerován a stažen.',
    'Toggle All' => 'Vybrat vše',
    'grid-export' => 'export',
];
