<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Comma Separated Values' => 'Значения, разделенные запятыми',
    'Download exported file' => 'Скачать экспортированный файл',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Exported File' => 'Экспортированный файл',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Язык гипертекстовой разметки',
    'Input error' => 'Ошибка ввода',
    'Key' => 'Ключ',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'PDF' => 'PDF',
    'Pick from list' => 'Выбрать из списка',
    'Please pick a value from the drop-down list.' => 'Пожалуйста, выберите значение из выпадающего списка.',
    'Portable Document Format' => 'Формат переносимого документа',
    'Tab Delimited Text' => 'Текст с разделителями табуляции',
    'Text' => 'Текст',
    'Value' => 'Значение',
    'Value is not in list.' => 'Значение отсутствует в списке.',
    'grid-export' => 'grid-export',
    'Column' => 'Поле',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Отключите блокировку всплывающих окон в вашем браузере, чтобы это не мешало загрузке.',
    'Export data in selected format' => 'Выберите формат файла для экспорта',
    'Generating the export file. Please wait...' => 'Файл экспорта генерируется, ожидайте...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Файл сгенерирован при помощи Krajee ExportMenu widget (yii2-export)',
    'Ok to proceed?' => 'Продолжить?',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Запрос принят. Вы можете закрыть это окно после окончания загрузки файла.',
    'Select Columns' => 'Поля для экспорта',
    'Select columns to export' => 'Выберите поля для экспорта',
    'The CSV export file will be generated for download.' => 'Будет сгенерирован файл в формате CSV.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Будет сгенерирован файл в формате EXCEL 2007+ (xlsx).',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Будет сгенерирован файл в формате EXCEL 95+ (xls).',
    'The HTML export file will be generated for download.' => 'Будет сгенерирован файл в формате HTML.',
    'The PDF export file will be generated for download.' => 'Будет сгенерирован файл в формате PDF.',
    'The TEXT export file will be generated for download.' => 'Будет сгенерирован файл в формате TEXT.',
    'Toggle All' => 'Выбрать все',
];
