<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => 'Поле',
    'Comma Separated Values' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Отключите блокировку всплывающих окон в вашем браузере, чтобы это не мешало загрузке.',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => 'Выберите формат файла для экспорта',
    'Generating the export file. Please wait...' => 'Файл экспорта генерируется, ожидайте...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Файл сгенерирован при помощи Krajee ExportMenu widget (yii2-export)',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => 'Продолжить?',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Запрос принят. Вы можете закрыть это окно после окончания загрузки файла.',
    'Select Columns' => 'Поля для экспорта',
    'Select columns to export' => 'Выберите поля для экспорта',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV export file will be generated for download.' => 'Будет сгенерирован файл в формате CSV.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Будет сгенерирован файл в формате EXCEL 2007+ (xlsx).',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Будет сгенерирован файл в формате EXCEL 95+ (xls).',
    'The HTML export file will be generated for download.' => 'Будет сгенерирован файл в формате HTML.',
    'The PDF export file will be generated for download.' => 'Будет сгенерирован файл в формате PDF.',
    'The TEXT export file will be generated for download.' => 'Будет сгенерирован файл в формате TEXT.',
    'grid-export' => '',
    'Toggle All' => 'Выбрать все',
];
