<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Column' => 'Cột',
    'Comma Separated Values' => 'Dấu phẩy phân cách giá trị',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Tắt chặn popup của trình duyệt để chắc chắn tải về.',
    'Download exported file' => 'Tải tiệp xuất giữ liệu',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Export data in selected format' => 'Xuất dữ liệu theo mẫu được chọn',
    'Exported File' => 'Xuất ra tiệp',
    'Generating the export file. Please wait...' => 'Đang xuất ra tiệp. Vui lòng chờ...',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Microsoft Excel 2007+ (xlsx)' => 'Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Excel 95+ (xls)',
    'Ok to proceed?' => 'Đồng ý thực hiện',
    'PDF' => 'PDF',
    'Portable Document Format' => 'PDF',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Yêu cầu đã được gửi! Bạn có thể đóng cửa sổ sau khi hoàn tất tải tiệp',
    'Select Columns' => 'Chọn Cột',
    'Select columns to export' => 'Chọn cột để xuất dữ liệu',
    'Tab Delimited Text' => 'Phân cách dữ liệu bằng Tab',
    'Text' => 'Văn Bản (Text)',
    'The CSV export file will be generated for download.' => 'Tiệp CSV sẽ được xuất để tải về.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Tiệp EXCEL 95+ (xlsx) sẽ được xuất để tải về.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Tiệp EXCEL 95+ (xls) sẽ được xuất để tải về.',
    'The HTML export file will be generated for download.' => 'Tiệp HTML sẽ được xuất để tải về.',
    'The PDF export file will be generated for download.' => 'Tiệp PDF sẽ được xuất để tải về.',
    'The TEXT export file will be generated for download.' => 'Tiệp TXT sẽ được xuất để tải về.',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => '',
    'Input error' => '',
    'Key' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'grid-export' => '',
    'Toggle All' => '@@@@',
];
