<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => 'Columna',
    'Comma Separated Values' => 'Valores Separados por Coma',
    'Download exported file' => 'Descargar archivo exportado',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Desactive bloqueadores de ventanas emergentes para asegurar una descarga correcta.',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => 'Exportar datos en el formato seleccionado',
    'Exported File' => 'Archivo Exportado',
    'Generating the export file. Please wait...' => 'Generando el archivo de exportación. Por favor espere...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Exportación de grilla generada por Krajee ExportMenu (yii2-export)',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => '¿Ok para continuar?',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '¡Solicitud enviada! Puede cerrar este diálogo después de guardar el archivo descargado.',
    'Select Columns' => 'Seleccionar Columnas',
    'Select columns to export' => 'Seleccionar columnas a exportar',
    'Tab Delimited Text' => 'Texto Delimitado por Tabulaciones',
    'Text' => '',
    'The CSV export file will be generated for download.' => 'El archivo CSV será generado para descargar',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'El archivo EXCEL 2007+ (xlsx) será generado para descargar',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'El archivo EXCEL 95+ (xls) será generado para descargar',
    'The HTML export file will be generated for download.' => 'El archivo HTML será generado para descargar',
    'The PDF export file will be generated for download.' => 'El archivo PDF será generado para descargar',
    'The TEXT export file will be generated for download.' => 'El archivo TEXT será generado para descargar',
    'grid-export' => '',
    'Toggle All' => 'Mostrar Todos',
];
