<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Column' => 'ستون',
    'Comma Separated Values' => 'مقادیر جدا شده به وسیله کاما',
    'Disable any popup blockers in your browser to ensure proper download.' => 'برای اطمینان از صحت دانلود، مسدود کننده پاپ آپ مرورگر خود را غیر فعال کنید.',
    'Download exported file' => 'دانلود فایل خروجی',
    'Export data in selected format' => 'خروجی داده در فرمت انتخابی',
    'Exported File' => 'فایل خروجی',
    'Generating the export file. Please wait...' => 'در حال تولید فایل خروجی. لطفا منتظر باشید',
    'Hyper Text Markup Language' => 'زبان نشانه گذاری اَبَر متن',
    'Input error' => 'خطای ورودی',
    'Key' => 'کلید',
    'Ok to proceed?' => 'تایید برای پردازش؟',
    'Pick from list' => 'انتخاب از لیست',
    'Please pick a value from the drop-down list.' => 'لطفا مقداری را از لیست کشویی انتخاب نمایید.',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'درخواست ارسال شد! شما با خیال راحت ممکن می‌توانید این صفحه را پس از ذخیره فایل های دانلود شده خود ببندید.',
    'Select Columns' => 'انتخاب ستون‌ها',
    'Select columns to export' => 'انتخاب ستون‌ها برای خروجی',
    'Tab Delimited Text' => 'متن جدا شده با Tab',
    'Text' => 'متن',
    'The CSV export file will be generated for download.' => 'فایل CSV خروجی برای دانلود ایجاد خواهد شد.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'فایل EXCEL 2007+ (xlsx) خروجی برای دانلود ایجاد خواهد شد.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'فایل EXCEL 95+ (xls) خروجی برای دانلود ایجاد خواهد شد.',
    'The HTML export file will be generated for download.' => 'فایل HTML خروجی برای دانلود ایجاد خواهد شد.',
    'The PDF export file will be generated for download.' => 'فایل PDF خروجی برای دانلود ایجاد خواهد شد.',
    'The TEXT export file will be generated for download.' => 'فایل TEXT خروجی برای دانلود ایجاد خواهد شد.',
    'Value' => 'مقدار',
    'Value is not in list.' => 'مقدار در لیست وجود ندارد',
    'grid-export' => 'خروجی گرید',
    'CSV' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => '',
    'HTML' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'PDF' => '',
    'Portable Document Format' => '',
    'Toggle All' => '@@همه را تغییر دهید@@',
];
