<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => 'Champ',
    'Comma Separated Values' => '',
    'Download exported file' => 'Télécharger le fichier',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Veuillez désactiver les pop-ups dans votre navigateur afin de garantir un téléchargement correct',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => 'Exporter dans le format sélectionné',
    'Exported File' => 'Fichier exporté',
    'Generating the export file. Please wait...' => 'Génération de l\'exportation. Veuillez patienter...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => 'Continuer?',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Requête envoyée! Vous pourrez fermer cette fenêtre une fois le fichier téléchargé',
    'Select Columns' => 'Choisir les champs',
    'Select columns to export' => 'Choisir les champs à exporter',
    'Tab Delimited Text' => '',
    'Text' => 'Texte',
    'The CSV export file will be generated for download.' => 'Le fichier CSV va être généré',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Le fichier Excel va être généré',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Le fichier Excel va être généré',
    'The HTML export file will be generated for download.' => 'Le fichier HTML va être généré',
    'The PDF export file will be generated for download.' => 'Le fichier PDF va être généré',
    'The TEXT export file will be generated for download.' => 'Le fichier texte va être généré',
    'grid-export' => '',
    'Toggle All' => '(Dé)selectionner tout',
];
