<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => 'Oszlop',
    'Comma Separated Values' => 'Vesszővel tagolt értékek',
    'Download exported file' => 'Exportfájl letöltése',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Kapcsoljon ki minden felugró ablak blokkolót a böngészőjében a sikeres letöltés érdekében.',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => 'Adat exportálása a kiválasztott formátumban',
    'Exported File' => 'Exportált fájl',
    'Generating the export file. Please wait...' => 'Export fájl előkészítése letöltésre. Várjon...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Export készítő: Krajee ExportMenu widget (yii2-export)',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => 'Folytathatjuk?',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Kérés elküldve! Letöltés után az ablakot bezárhatja.',
    'Select Columns' => 'Oszlopok kiválasztása',
    'Select columns to export' => 'Exportálandó oszlopok kiválasztása',
    'Tab Delimited Text' => 'Tabulátorral tagolt szöveg',
    'Text' => 'Szöveg',
    'The CSV export file will be generated for download.' => 'A CSV fájl előkészítése letöltésre.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Az EXCEL 2007+ (xlsx) fájl előkészítése letöltésre.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Az EXCEL fájl előkészítése letöltésre.',
    'The HTML export file will be generated for download.' => 'A HTML fájl előkészítése letöltésre.',
    'The PDF export file will be generated for download.' => 'A PDF fájl előkészítése a letöltésre.',
    'The TEXT export file will be generated for download.' => 'A szöveges export fájl előkészítése letöltésre.',
    'grid-export' => '',
    'Toggle All' => 'Összes kijelölése',
];
