<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Column' => 'Kolom',
    'Comma Separated Values' => 'Komma gescheiden waardes',
    'Download exported file' => 'Download geëxporteerd bestand',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Schakel alle pop-up blockers uit om een correcte download te garanderen.',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Export data in selected format' => 'Exporteer data in het geselecteerde format',
    'Exported File' => 'Geëxporteerd bestand',
    'Generating the export file. Please wait...' => 'Het export bestand wordt gegenereerd. Even geduld alstublieft...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Raster export gegenereerd door Krajee ExportMenu widget (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' =>  'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'Akkoord om verder te gaan?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Aanvraag verstuurd! U mag deze dialoog veilig afsluiten na het downloaden van uw bestand.',
    'Select Columns' => 'Selecteer kolommen',
    'Select columns to export' => 'Selecteer kolommen om te exporteren',
    'Tab Delimited Text' => 'Tabs gescheiden tekst',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'Het CSV export bestand zal gegenereerd worden om te downloaden',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Het EXCEL 2007+ (xlsx) export bestand zal gegenereerd worden om te downloaden',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Het EXCEL 95+ (xls) export bestand zal gegenereerd worden om te downloaden',
    'The HTML export file will be generated for download.' => 'Het HTML export bestand zal gegenereerd worden om te downloaden',
    'The PDF export file will be generated for download.' => 'Het PDF export bestand zal gegenereerd worden om te downloaden',
    'The TEXT export file will be generated for download.' => 'Het TEXT export bestand zal gegenereerd worden om te downloaden',
    'grid-export' => 'raster-export',
    'Toggle All' => 'Wissel alles',
];
