<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => '列',
    'Comma Separated Values' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => '请禁用浏览器弹出窗拦截器以确保正常下载。',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => '以选定格式导出数据',
    'Generating the export file. Please wait...' => '正在生成导出文件，请稍后...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => '表格数据由Krajee的ExportMenu组件(yii2-export)生成导出',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => '确定继续?',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '请求已提交!你可以在下载完文件后安全地关闭本对话框。',
    'Select Columns' => '选择列',
    'Select columns to export' => '选择导出列',
    'Tab Delimited Text' => 'Tab分隔的文本',
    'Text' => '',
    'The CSV export file will be generated for download.' => 'CSV文件即将生成下载。',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'EXCEL 2007+ (xlsx)文件即将生成下载。',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'EXCEL 95+ (xls)文件即将生成下载。',
    'The HTML export file will be generated for download.' => 'HTML文件即将生成下载。',
    'The PDF export file will be generated for download.' => 'PDF文件即将生成下载。',
    'The TEXT export file will be generated for download.' => 'TEXT文件即将生成下载。',
    'grid-export' => '表格导出',
    'Toggle All' => '反选所有',
];

