<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Input error' => '',
    'Key' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'grid-export' => '',
    'CSV' => 'CSV',
    'Column' => 'Сповпець',
    'Comma Separated Values' => 'Розділені комами значення',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Вимкніть блокування спливаючих вікон у вашому браузері, щоб це не заважало завантаженні.',
    'Download exported file' => 'Завантажити експортований файл',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95+',
    'Export data in selected format' => 'Оберіть формат файлу для експорту',
    'Exported File' => 'Експортований файл',
    'Generating the export file. Please wait...' => 'Файл експорту генерується, очікуйте...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Файл згенерований за допомогою Krajee ExportMenu widget (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Мова розмітки гіпертексту (Веб-сторінка)',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'Продовжити?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Портативний формат документа',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Запит прийнятий. Ви можете закрити це вікно після закінчення завантаження файлу.',
    'Select Columns' => 'Стовпці для експорту',
    'Select columns to export' => 'Оберіть стовпці для експорту',
    'Tab Delimited Text' => 'Розділений текст вкладок',
    'Text' => 'Текст',
    'The CSV export file will be generated for download.' => 'Згенерується файл у форматі CSV.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Згенерується файл у форматі EXCEL 2007+ (xlsx).',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Згенерується файл у форматі EXCEL 95+ (xls).',
    'The HTML export file will be generated for download.' => 'Згенерується файл у форматі HTML.',
    'The PDF export file will be generated for download.' => 'Згенерується файл у форматі PDF.',
    'The TEXT export file will be generated for download.' => 'Згенерується файл у форматі TEXT.',
    'Toggle All' => 'Усі',
];
