<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Column' => 'Stulpelis',
    'Comma Separated Values' => 'Kableliu atskirtos reikšmės',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Kad sklandžiai veiktų failo parsisiuntimas, atjunkite visus reklaminių langų blokuotojus.',
    'Download exported file' => 'Parsisiųsti eksportuotą failą',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Export data in selected format' => 'Eksportuoti duomenis pasirinktu formatu',
    'Exported File' => 'Eksportuotas Failas',
    'Generating the export file. Please wait...' => 'Generuojamas eksporto failas. Prašome palaukti...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Lentelės eksportas sugeneruotas su Krajee ExportMenu widget (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'Galima tęsti?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Užklausa išsiųsta! Užsisaugoję failą, galite uždaryti dialogo langą.',
    'Select Columns' => 'Pasirinkti Stulpelius',
    'Select columns to export' => 'Pasirinkti eksportuojamus stulpelius',
    'Tab Delimited Text' => 'Tabuliacija atskirtas tekstas',
    'Text' => 'Tekstas',
    'The CSV export file will be generated for download.' => 'Bus sugeneruotas CSV eksporto failas parsisiuntimui.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Bus sugeneruotas EXCEL 2007+ (xlsx) eksporto failas parsisiuntimui.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Bus sugeneruotas EXCEL 95+ (xls) eksporto failas parsisiuntimui.',
    'The HTML export file will be generated for download.' => 'Bus sugeneruotas HTML eksporto failas parsisiuntimui.',
    'The PDF export file will be generated for download.' => 'Bus sugeneruotas PDF eksporto failas parsisiuntimui.',
    'The TEXT export file will be generated for download.' => 'Bus sugeneruotas TEXT eksporto failas parsisiuntimui.',
    'grid-export' => 'lentelės eksportas',
    'Input error' => '',
    'Key' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'Toggle All' => '@@Žymėti visus@@',
];
