<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Export data in selected format' => '',
    'Select Columns' => '',
    'Select columns to export' => '',
    'CSV' => 'CSV',
    'Comma Separated Values' => 'Valores separados por vírgula',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Desactive qualquer bloqueador de popups no seu browser para garantir o correcto download',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95 +',
    'Generating the export file. Please wait...' => 'A gerar o ficheiro para exportar. Por favor aguarde...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Exportador de tabelas criado por Krajee ExportMenu widget (yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Linguagem de Marcação de Hipertexto',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'Ok para continuar?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Documento em formato PDF',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Pedido submetido! Pode fechar esta janela depois de finalizado o download do ficheiro',
    'Tab Delimited Text' => 'Texto delimitado por tabulações',
    'Text' => 'Texto',
    'The CSV export file will be generated for download.' => 'O ficheiro CSV será gerado para download',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'O ficheiro EXCEL 2007+ (xlsx) será gerado para download',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'O ficheiro EXCEL 95+ (xls) será gerado para download',
    'The HTML export file will be generated for download.' => 'O ficheiro HTML será gerado para download',
    'The PDF export file will be generated for download.' => 'O ficheiro PDF será gerado para download',
    'The TEXT export file will be generated for download.' => 'O ficheiro de Texto será gerado para download',
    'grid-export' => 'grid-export',
];
