<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Input error' => '',
    'Key' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'PDF' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Portable Document Format' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'grid-export' => '',
    'Column' => 'Colonna',
    'Comma Separated Values' => 'Valori Separati Da Virgole',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Disabilita qualsiasi blockers popup nel tuo browser per permettere il download',
    'Download exported file' => 'Scarica il file esportato',
    'Export data in selected format' => 'Esporta i dati nel formato selezionato',
    'Exported File' => 'File Esportato',
    'Generating the export file. Please wait...' => 'Generazione del file da esportare. Attendere...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Esportazione Grid generata da Krajee ExportMenu widget (yii2-export)',
    'Ok to proceed?' => 'Procedere?',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Richiesta sottomessa! Puoi chiudere in sicurezza questa finestra dopo aver scaricato il file',
    'Select Columns' => 'Seleziona Colonne',
    'Select columns to export' => 'Seleziona colonne da esportare',
    'Tab Delimited Text' => 'Il Testo Delimitato Dal Tab',
    'Text' => 'Testo',
    'The CSV export file will be generated for download.' => 'Il file esportato in CSV sarà generato per il download',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Il file esportato in EXCEL 2007+ (xlsx) sarà generato per il download',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Il file esportato in EXCEL 95+ (xls) sarà generato per il download',
    'The HTML export file will be generated for download.' => 'Il file esportato in HTML sarà generato per il download',
    'The PDF export file will be generated for download.' => 'Il file esportato in PDF sarà generato per il download',
    'The TEXT export file will be generated for download.' => 'Il file esportato in TEXT sarà generato per il download',
    'Toggle All' => 'Seleziona Tutti',
];
