<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Column' => 'Kolumna',
    'Comma Separated Values' => 'Wartości rozdzielone przecinkiem',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Wyłącz blokowanie okien aby poprawnie pobrać plik',
    'Download exported file' => 'Pobierz plik',
    'Export data in selected format' => 'Eksport danych w wybranym formacie',
    'Exported File' => 'Plik',
    'Generating the export file. Please wait...' => 'Trwa generowanie pliku. Proszę czekać...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Wygenerowane przez Krajee ExportMenu widget (yii2-export)',
    'Ok to proceed?' => 'Wykonać?',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Można zamknąć to okno po pobraniu pliku.',
    'Select Columns' => 'Wybierz kolumny',
    'Select columns to export' => 'Wybierz kolumny do eksportu',
    'Tab Delimited Text' => 'Tekst rozdzielony tabulatorem',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'Plik CSV zostanie wygenerowany do pobrania.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'Plik EXCEL 2007+ (xlsx) zostanie wygenerowany do pobrania.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Plik EXCEL 95+ (xls) zostanie wygenerowany do pobrania.',
    'The HTML export file will be generated for download.' => 'Plik HTML zostanie wygenerowany do pobrania.',
    'The PDF export file will be generated for download.' => 'Plik PDF zostanie wygenerowany do pobrania.',
    'The TEXT export file will be generated for download.' => 'Plik tekstowy zostanie wygenerowany do pobrania.',
    'grid-export' => 'eksport',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Input error' => '',
    'Key' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'PDF' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Portable Document Format' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'Toggle All' => '@@Przełącz wszystkie@@',
];
