<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data as Comma Separated Values (CSV). Ok to proceed?' => '',
    'Export data as Excel 2007+ (xlsx) format. Ok to proceed?' => '',
    'Export data as Excel 95+ (xls) format. Ok to proceed?' => '',
    'Export data as Portable Document Format (PDF). Ok to proceed?' => '',
    'Export data as a HTML file. Ok to proceed?' => '',
    'ExportWorksheet' => '',
    'HTML' => '',
    'PDF' => '',
    'Save as CSV' => '',
    'Save as Excel (xls)' => '',
    'Save as Excel (xlsx)' => '',
    'Save as HTML' => '',
    'Save as PDF' => '',
    'grid-export' => '',
];
