<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => '',
    'Comma Separated Values' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => '',
    'Download exported file' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Export data in selected format' => '',
    'Exported File' => '',
    'Generating the export file. Please wait...' => '',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Select Columns' => '',
    'Select columns to export' => '',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => '',
    'The EXCEL 95+ (xls) export file will be generated for download.' => '',
    'The HTML export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'Toggle All' => '',
    'grid-export' => '',
];
