<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Download exported file' => '',
    'Exported File' => '',
    'Input error' => '',
    'Key' => '',
    'Pick from list' => '',
    'Please pick a value from the drop-down list.' => '',
    'Value' => '',
    'Value is not in list.' => '',
    'CSV' => 'CSV',
    'Column' => 'Alan',
    'Comma Separated Values' => 'Virgülle Ayrılmış Değerler',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Düzgün bir indirme için tarayıcınızın açılır pencere engelleyicilerini devredışı bırakın.',
    'Excel 2007+' => 'Excel 2007+',
    'Excel 95 +' => 'Excel 95+',
    'Export data in selected format' => 'Veriyi seçilen formatta dışa aktar',
    'Generating the export file. Please wait...' => 'Dışa çıkarılacak dosya oluşturuluyor. Lütfen bekleyiniz...',
    'Grid export generated by Krajee ExportMenu widget (yii2-export)' => 'Izgara dışa aktarımı Krajee Export Menu aracıyla oluşturuldu(yii2-export)',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hiper Metin İşaretleme Dili',
    'Microsoft Excel 2007+ (xlsx)' => 'Microsoft Excel 2007+ (xlsx)',
    'Microsoft Excel 95+ (xls)' => 'Microsoft Excel 95+ (xls)',
    'Ok to proceed?' => 'İşlemek için OK?',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Taşınabilir Döküman Formatı',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'İstek alındı! İndirilen dosyayı kaydettikten sonra bu pencereyi kapatabilirsiniz.',
    'Select Columns' => 'Alanları Seç',
    'Select columns to export' => 'Dışa aktarmak için alanları seç',
    'Tab Delimited Text' => 'Sekme Sınırlandırılmış Metin',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'İndirmek için CSV aktarım dosyası oluşturulacak.',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => 'İndirmek için EXCEL 2007+ (xlsx)  aktarım dosyası oluşturulacak.',
    'The EXCEL 95+ (xls) export file will be generated for download.' => 'Excel 95+ (xls) aktarım dosyası oluşturulacak.',
    'The HTML export file will be generated for download.' => 'HTML aktarım dosyası oluşturulacak.',
    'The PDF export file will be generated for download.' => 'PDF aktarım dosyası oluşturulacak.',
    'The TEXT export file will be generated for download.' => 'Text aktarım dosyası oluşturulacak.',
    'Toggle All' => 'Tümünü seç',
    'grid-export' => 'export',
];
